// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Messages sent from the client to the server over WebSocket.
 */
export type ClientMessage = { "type": "connect", version: number, token: string, 
/**
 * Team context for this connection.
 */
team_id: string, 
/**
 * Source/type subscriptions, e.g. ["source:github", "type:push"] or ["*"]
 */
scopes: Array<string>, 
/**
 * Optional stable client identifier for cursor resumption.
 */
client_id: string | null, } | { "type": "ack", seq: bigint, } | { "type": "request", id: string, method: string, params: JsonValue, };
