// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Messages sent from the server to the client over WebSocket.
 */
export type ServerMessage = { "type": "connected", last_seq: bigint, client_id: string, } | { "type": "cursor_expired", oldest_available_seq: bigint, message: string, } | { "type": "event", seq: bigint, 
/**
 * The CloudEvent serialized as JSON value.
 * We use serde_json::Value here because cloudevents::Event
 * doesn't implement TS, and for WS transport we serialize it anyway.
 */
event: JsonValue, } | { "type": "response", id: string, ok: boolean, payload: JsonValue, } | { "type": "error", code: number, message: string, } | { "type": "quota_snapshot", provider: string, events_used: bigint, events_limit: bigint, current_period_end: string, } | { "type": "billing_block", provider: string, reason: string, retryable: boolean, action: JsonValue, };
